feat: OVERVIEW PAGE add overview banner page - MEED-551 - Meeds-io/MIPs#10
Meeds-io/meeds pull request #339
Opened 2022-10-16 23:50 UTC by ArfaouiMohamedAmine

this change is going to add an overview banner page where 'OverviewBanner' portlet is implemented .

2022-10-21 17:03 UTC, AzmiTouil requested changes

2022-10-21 17:03 UTC, AzmiTouil commented on webapps/plf-meeds-extension/src/main/webapp/WEB-INF/conf/meeds/portal/meeds/pages.xml
> +    </container>
reformat code please!

2022-10-21 17:19 UTC, ArfaouiMohamedAmine commented on webapps/plf-meeds-extension/src/main/webapp/WEB-INF/conf/meeds/portal/meeds/pages.xml
> +    </container>
@AzmiTouil  done

2022-10-25 10:00 UTC, AzmiTouil approved these changes

2022-10-25 10:06 UTC, merged